name: biz_track
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.2.1+1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  flutter_svg: ^1.0.3
  google_fonts: ^2.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.3.6
  intl: ^0.18.1
  loading_overlay: ^0.3.0
  lottie: null
  pretty_dio_logger: ^1.3.1
  flutter_barcode_scanner: ^2.0.0
  bluetooth_print: ^4.3.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  fonts:
    - family: Apercu
      fonts:
        - asset: assets/fonts/Apercu-Regular.otf
        - asset: assets/fonts/Apercu-Italic.otf
          style: italic
        - asset: assets/fonts/Apercu-Bold.otf
          weight: 700

  assets:
    - assets/svg/
    - assets/png/
    - assets/fonts/
    - assets/
